name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/html"

      - name: Run update script
        run: |
          ssh -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd /var/www/html && git pull'
